version: "3.1"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
  user-interaction-service:
    build: ./user-interaction-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  content-service:
    build: ./content-service
    ports:
      - "3001:3001"
    depends_on:
      - user-interaction-service
      - mongo

volumes:
    data-db: