version: "2"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db
  user-interaction-service:
    build: ./user-interaction-service
    ports:
      - "3000:3000"
  content-service:
    build: ./content-service
    ports:
      - "3001:3001"

volumes:
    data-db: